// SPDX-FileCopyrightText: 2026 MesTTo
//
// SPDX-License-Identifier: MIT

// @metta-ts/edsl: typed TypeScript builders for MeTTa. `names()` and `vars()` mint symbols/functors and
// logic variables from proxies; capitalized combinators (`If`/`Let`/`Match`/…) build the special forms;
// tagged templates (`m`) cover raw MeTTa source; `mettaDB()` runs it all on the existing interpreter.
// Any JS value auto-grounds, and the runner bridges both directions (`fn`/`fns` in, `call`/`import` out).
export {
  type Term,
  type Var,
  type VarValue,
  type Name,
  type Names,
  type Vars,
  type NamedVars,
  type NamedNames,
  type Grounded,
  names,
  vars,
  val,
  ground,
  patternVars,
  e,
  sym,
  nil,
  list,
} from "./term";
export {
  rel,
  type Relation,
  type Pattern,
  type RowOf,
  type RowResult,
  type Anonymous,
} from "./relation";
export {
  rule,
  decl,
  arrow,
  If,
  Case,
  Let,
  LetStar,
  Match,
  All,
  Superpose,
  Collapse,
  Empty,
  Unify,
  Sealed,
  Quote,
  add,
  sub,
  mul,
  div,
  mod,
  eq,
  neq,
  gt,
  lt,
  ge,
  le,
  and,
  or,
  not,
  carAtom,
  cdrAtom,
  consAtom,
  deconsAtom,
  getType,
  getMetatype,
  assertEqual,
  assertAlphaEqual,
  unique,
  union,
  intersection,
  subtraction,
  println,
  jsonEncode,
  jsonDecode,
  dictSpace,
  getKeys,
  getValue,
  addAtom,
  addReduct,
  addAtoms,
  addReducts,
  removeAtom,
  getAtoms,
  newSpace,
  contextSpace,
  sizeAtom,
  indexAtom,
  atomSubst,
  firstFromPair,
  minAtom,
  maxAtom,
  mapAtom,
  filterAtom,
  foldlAtom,
  forEachInAtom,
  ifDeconsExpr,
  Switch,
  Chain,
  Eval,
  Function,
  Return,
  NoEval,
  Id,
  CollapseBind,
  SuperposeBind,
  Capture,
  typeCast,
  isFunction,
  matchTypes,
  newState,
  changeState,
  getState,
  ErrorAtom,
  IfError,
  returnOnError,
  Try,
  Catch,
  assertEqualToResult,
  assertAlphaEqualToResult,
  assertEqualMsg,
  assertAlphaEqualMsg,
  assertIncludes,
  assert,
  pow,
  sqrt,
  abs,
  log,
  trunc,
  ceil,
  floor,
  round,
  sin,
  asin,
  cos,
  acos,
  tan,
  atan,
  isNaN_,
  isInf,
  randomInt,
  randomFloat,
  xor,
  parseAtom,
  repr,
  stringToChars,
  charsToString,
  formatArgs,
  trace,
  getDoc,
  help,
  bind,
  pragma,
  importModule,
  registerModule,
  gitModule,
  nop,
} from "./forms";
export { M, type Chain as ChainOf, type ChainSteps, type Evaluator } from "./chain";
export { m, mAll, parseSource } from "./template";
export { type SourceVars, type SourceRow, type SchemaRow } from "./source-vars";
export {
  type SExprRow,
  type SExprCheck,
  type JoinRow,
  type RowCheck,
  type ColumnTypeError,
  type VarConflictError,
} from "./sexpr";
export {
  MettaDB,
  mettaDB,
  type Row,
  type ImportedFn,
  type AwaitProxy,
  type CallProxy,
  type FnSchema,
  type RelSchema,
  type DbSchema,
} from "./db";

// Re-export hyperon atom types for annotations without a second import.
export { Atom, type GroundedAtom, ValueAtom, atomToJs } from "@mettascript/hyperon";
export { type JoinCheck } from "./sexpr";
export { SpaceView, type SpaceLike, type FactOf } from "./space";
export { isErrorAtom, errorAtoms, errorParts, errorText, raiseErrors, MettaError } from "./errors";
export { decodeWith, decodeWithAsync, SchemaError, type StandardSchemaV1 } from "./schema";
export { whyEmpty, formatWhyEmpty, type WhyEmpty, type NearMiss } from "./explain";
export {
  Self,
  True,
  False,
  SymbolType,
  ExpressionType,
  VariableType,
  GroundedType,
  AtomType,
  TypeType,
  NumberType,
  StringType,
  BoolType,
  Undefined,
  ErrorType,
  BadType,
  IncorrectNumberOfArguments,
} from "./known";
export {
  matchAtom,
  isMatching,
  matchBindings,
  AtomMatch,
  NonExhaustiveError,
  P,
  type Matcher,
  type Binds,
  type BindingsOf,
  type NonExhaustive,
  type ExhaustiveNeedsSchema,
} from "./match-atom";
export {
  mettaModule,
  MettaModule,
  type ModuleHost,
  type SchemaOf,
  type WithModule,
} from "./module";
export { formatChanges, type Change, type TxReport } from "./transaction";
// Re-exported so a versioned named space needs one import, not two.
export { PersistentSpace, type Space, type SpaceVersion } from "@mettascript/hyperon";
