// SPDX-FileCopyrightText: 2026 MesTTo
//
// SPDX-License-Identifier: MIT

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const sourceDir = join(root, "src", "metta");
const outputFile = join(root, "src", "generated", "module.ts");
const check = process.argv.includes("--check");

const fragments = readdirSync(sourceDir)
  .filter((name) => /^\d{2}-.*\.metta$/.test(name))
  .sort();

if (fragments.length === 0) {
  throw new Error("no numbered MeTTa source fragments found");
}

const source = fragments
  .map((name) => readFileSync(join(sourceDir, name), "utf8").trimEnd())
  .join("\n\n");
const generated = await format(
  [
    "// SPDX-FileCopyrightText: 2026 MesTTo",
    "//",
    "// SPDX-License-Identifier: MIT",
    "",
    "// Generated by scripts/generate-module.mjs. Do not edit.",
    `export const FUZZ_MODULE_SRC = ${JSON.stringify(source + "\n")};`,
    "",
  ].join("\n"),
  { parser: "typescript" },
);

if (check) {
  let current;
  try {
    current = readFileSync(outputFile, "utf8");
  } catch {
    throw new Error("generated fuzz module is missing; run pnpm generate");
  }
  if (current !== generated) {
    throw new Error("generated fuzz module is stale; run pnpm generate");
  }
} else {
  mkdirSync(dirname(outputFile), { recursive: true });
  writeFileSync(outputFile, generated);
}
